name: synthetic-battery-data
channels:
  - pytorch
  - numba
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _pytorch_select=0.1
  - _tflow_select=2.1.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cachetools=4.2.2
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.5
  - contourpy=1.0.5
  - cryptography=38.0.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.6.0
  - ipywidgets=8.0.3
  - jedi=0.18.1
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.4.7
  - jupyter_core=4.11.2
  - jupyterlab_widgets=3.0.4
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvmlite=0.38.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.33
  - nss=3.74
  - numba=0.55.2
  - numexpr=2.8.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.2.1
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.3.4
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prompt-toolkit=3.0.20
  - protobuf=3.20.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - python_abi=3.8
  - pytorch=1.7.1
  - pytz=2022.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.4.1
  - termcolor=2.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.7.2
  - torchinfo=1.7.1
  - torchvision=0.8.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing_extensions=4.4.0
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=4.0.4
  - wrapt=1.14.1
  - xz=5.2.8
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.2
